### ISSUE TITLE
Add ability to remove modules from the storage

### ISSUE THREAD

**Issue by marpio** [gomods/athens#1004]
**Is your feature request related to a problem? Please describe.**
Even though athens storage should be immutable, there are some cases where modules will have to be deleted i.e. due to a DMCA infringement.

**Describe the solution you'd like**
The storages already implements the `Deleter` interface, what's missing is an http endpoint. It might be an manual process only possible from the UI and only accessible to users with a specific permission.

**Comment by arschles** [comment]
we'll need to have some authorization mechanism for deletes

**Comment by lopezator** [comment]
This would be possible now, although not ideal, by using "basic auth". 

I agree that we need something to delete specific packages in case something goes bad (bad checksum, corrupted package or whatever).

**Comment by arschles** [comment]
We have [external storage drivers](https://github.com/gomods/athens/pull/1587) now, so an external driver could be built, using the Athens `pkg/storage` packages, that supports deletions. I'm going to close this for now since there hasn't been activity here in a long time. If anyone comes across this issue and has a definitive use case to having _Athens_ support deletions, please feel free to comment here or open up a new issue 😄
