### ISSUE TITLE
config file permission 

### ISSUE THREAD

**Issue by z2665** [gomods/athens#1007]
**Is your feature request related to a problem? Please describe.**
System ceontos 7.2
 I'm always frustrated when  I open with config.toml, the information show it need config file's permission is bit mask 077. Actually I use chmod 077 filename not work.
but chmod 700 work well.

**Describe the solution you'd like**
the suggest information may need more friendly.
E.g ''the config's permission may error. you can use chmod 700 file name to solve this problem'

**Comment by manugupt1** [comment]
This is what the error message shows

```
should have at most rwx,-, - (bit mask 077) as permission
```

Is there any confusion with `rwx, -, -`?

**Comment by z2665** [comment]
> This is what the error message shows
> 
> ```
> should have at most rwx,-, - (bit mask 077) as permission
> ```
> Is there any confusion with `rwx, -, -`?

It may about habit;. I try chmod 077 first. but  not work.

**Comment by manugupt1** [comment]
I am closing this issue as won't fix. I will fix it when someone else complains as well

If you still think it can be worded better, can you open a PR and we will go through it and merge?

**Comment by z2665** [comment]
Thanks.  I'll try open PR

**Comment by lanmingle** [comment]
Meaningless access control, disgusting to me

**Comment by mplachter** [comment]
I would like a way to either toggle this off or just remove it. This does add deployment complexity when running in a docker container as a random runtime user.

**Comment by arschles** [comment]
@lanmingle I apologize for not getting back to this issue sooner. I understand that lots of folks including you don't like the way that Athens treats permissions of the `config.toml`. Thank you for telling us that it's a problem for you, and that you're unhappy with it. 

However, next time can you please tell us in a more respectful way? Here is an example: "I don't think that this access control enforcement is helpful.". If you have an idea to make it better, please add that to your comment as well.

If you can post more constructive comments, then everybody in the community can help make the project better more quickly and easily.

Thanks very much

**Comment by arschles** [comment]
Since this issue is coming up again, I'd like to address it more completely. Sorry for our lack of attention earlier.

We do the permissions check [here](https://github.com/gomods/athens/blob/27f36834161274dd3b98f8547a1aea1f536f643d/pkg/config/config.go#L323). I haven't done binary AND calculations by hand in a while, but I think the calculation is right, and the error string is wrong. Hopefully someone can correct me if I'm wrong! @z2665 are you still ok with using `700`?


Generally speaking, we do the permissions check to try and ensure that nobody but the Athens user can read the file, since it may have sensitive data in it like cloud keys or TLS certificates, etc...

@mplachter we could add runtime configuration to disable this check, but I would certainly prefer to try and keep this as-is to help users avoid possibly leaking credentials and other sensitive data. When you start up the docker container, could you possibly add a line that `chmod`'s the config file just before you start Athens?

**Comment by z2665** [comment]
@arschles  Yeah,the calculation is right,but the error prompt may not be clear for me.  The error prompt will tell a bit mask value, but the value entered by using chmod to modify permissions should be the value masked by the bit mask. So I don't get it  at that time. I think this may cause some puzzled for first-time users.

**Comment by mplachter** [comment]
@arschles the issue comes into play when the docker runtime user is a UID of a random user that does not have a user group. Since the random user does not have a user group you cannot chown or chmod the files or directories.

**Comment by arschles** [comment]
@mplachter sorry for the delay. that problem sounds like a good reason to relax the perms requirement then! would a new env var work for you?

**Comment by apptut** [comment]
I encouter this problem too. I think this not good idea must limit config file mask to 0700

**Comment by lanmingle** [comment]
@arschles 该死的翻译，用词错误，对不起！

Damn translation, misnomer, sorry
