### ISSUE TITLE
Exists checks only for .mod

### ISSUE THREAD

**Issue by marpio** [gomods/athens#1032]
**Describe the bug**
At the moment we check for existence of a module by checking only if the `.mod` part is present in the storage. 
This can lead to a problem if saving the module failed on `info`, `zip` or both but succeeded on `mod` because now the `storage.Exists` func will report true even though only the `mod` is present.
This, depending on the storage leads to some problems - for one the `/info` and `/zip` endpoints will fail but `/mod` will succeed which may be confusing to the user. Whats even worse is that some of the storages use `Exists` while saving the module. In that case we will never be able to save the module again because athens thinks that it's already stashed.

Just thinking at loud but I think we should:
 - check if all the parts exists and not only `mod`.
 - let `Save` overwrite an existing part.

**Comment by manugupt1** [comment]
Hi Piotr,

I second what you are proposing.



Cheers,

Manu Gupta

**Comment by marpio** [comment]
@marwan-at-work 
> we should definitely not overwrite anything in my opinion. Once something is saved, it's saved forever. Unless the user wants to delete something explicitly.

In that case, what we have in storage is broken, so it can't be used anyway. Let's say the first time the mod@ver was requested (at time `t1`) athens managed to save `mod` and `info` but failed on `zip` so the whole operation fails. This state should be treated as if this mod@ver wasn't there at all so that when the user requests it again at `t2` we don't mix `mod` and `info` from `t1` and `zip` from `t2`.

> We can potentially make sure storage.Saver is responsible for saving everything otherwise it just cleans up after itself. Meaning, the contract on the Save method is all or nothing.

Can we guarantee that the cleanup always succeeds? The odds are that if `Save` fails the `Delete` fails as well i.e. because of some networking issue.

> Maybe a storage can give us the length of a directory..and in that way storage.Checker only needs to check if len == 3

:+1:

**Comment by marwan-at-work** [comment]
@marpio 

>This state should be treated as if this mod@ver wasn't there at all so that when the user requests it again at t2 we don't mix mod and info from t1 and zip from t2.

Yes, 100% which is why I suggested `storage.Save` ensures cleaning up after itself. We should definitely not be mixing objects around. 

By the way, exists returns `bool, error`, and so if `storage.Save` wasn't entirely successful storage.Exists can do the following: 

1. Attempt to delete everything, since `storage.Save` couldn't do it. 
2. If deletion failed, then return a helpful error message. 
3. If deletion succeeded, return `false, nil` 

I'm still just bouncing ideas, it's definitely worth thinking about a little more

**Comment by manugupt1** [comment]
I do not think we should let `Exists` overwrite / cleanup. For the save part, while I can see that overwrite may not be the best idea (checksum differs, module that was saved successfully has not been successfully written now because of a network failure), should we assume that something that is already on the storage is successfully written, but the ones that are not there are filled in successfully?

**Comment by marpio** [comment]
@manugupt1
Wenn should not overwrite anything that has been saved successfully, for sure.

**Comment by manugupt1** [comment]
We can selectively `Save` what needs to be saved by looking at `Exists` or even `Delete`. The state information tells us how much are we missing and we can act upon it within the context of the storage module. So, for example, if you do a Save(); You check for Exists(); you get a false / len = 2, that is not enough information to complete the module without over-writing the previous module. This can be a private function inside the storage package, which is called by `Exists` so that we do not break any other API, but the storage package uses it to appropriately save or not save.

I like the idea of error, the only change that I might have is return []errors, and have types like `ModNotFound`, `InfoNotFound` and `ZipNotFound`. So, that any inference is made.

**Comment by manugupt1** [comment]
I am confused as to how the stasher would know what needs to be overwritten as well, can you be a bit more explicit about that?

**Comment by marpio** [comment]
@marwan-at-work about your idea - that's actually what I had in mind - `Exists` returns false if the module is incomplete. Then we overwrite the incomplete objects since download protocol thinks the module is not present and calls `Stash`.
Or did I misunderstand and you mean something different?

@manugupt1 if a module is incomplete, we should not just add the missing objects because we could then have a mismatch between them. We should instead remove the old ones and stash the new.

**Comment by marpio** [comment]
`Exists` could also return `false` and some error indicating that the mod is incomplete and so download protocol could control if `Stash` overwrites or not. Is this what you meant @marwan-at-work ?

**Comment by marwan-at-work** [comment]
@marpio you understood me correctly the first time :) -- however, what if a storage.Backend returns an "already-exists" error and does not let us overwrite and object? For simplicity sake, let's assume that won't happen, but we should definitely double check *all* of our storages to make sure overwriting is ok. For example, GCP has an option where you can disable overwriting, and so Athens would break in this scenario.

**Comment by marwan-at-work** [comment]
@manugupt1 as Piotr mentioned, we should **not** do that :) See his comment above for why.

**Comment by arschles** [comment]
as an intermediate step, @manugupt1 @marpio @marwan-at-work do you think we can return false if the `.mod`, `.info` and `.zip` don't all exist? we can then move on and decide what to do in a follow-up PR

**Comment by marwan-at-work** [comment]
Most storages we implement allow overrides, so just returning `false` should be an ok thing for now. I can take on this issue and get back to some Athens work this weekend :) (unless anyone likes to work on it, feel free to let me know by Friday, happy to hand it over)

**Comment by arschles** [comment]
@marwan-at-work I'll submit a PR for now that just returns `false`
