### ISSUE TITLE
If there any solution to use athens like maven, we can deploy modules to athens, rather than to go get from gitlab or github

### ISSUE THREAD

**Issue by 12307** [gomods/athens#1047]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want to build a private module athens in our company, and use athens like maven, so we can deploy a version to the private repos.

**Describe alternatives you've considered**

**Additional context**

**Comment by gensmusic** [comment]
same question

**Comment by tomjamescn** [comment]
+1

**Comment by arschles** [comment]
Hey @12307, @gensmusic and @tomjamescn - did the explanation in https://github.com/gomods/athens/issues/1083#issuecomment-466727229 make sense?

If you have a specific use case that the pull-from-VCS mechanism from https://github.com/gomods/athens/issues/1083#issuecomment-466727229 doesn't solve, please write it in here so we can be aware and consider making changes to that or adding functionality.

Thanks all! 😀

**Comment by 12307** [comment]
i have found a solution to solve this problem. so thx arschles

**Comment by arschles** [comment]
@12307 not a problem 😁 

I'll close this issue but if you're able to share the solution, I'd love to hear it! Either write it in here or come say hi to us in the Gophers Slack `#athens` channel

**Comment by tomjamescn** [comment]
> i have found a solution to solve this problem. so thx arschles

what is the solution, can u share it ? thanks

**Comment by arschles** [comment]
@tomjamescn I don't know what the solution is obviously, but maybe I can help.

Athens doesn't have a "publish" feature (yet, but we'll consider it if you have a concrete use case!) because it automatically pulls from the private repository the first time you run a `go get`. In other words, it pulls code on-demand from the private repo. So, if you want to "publish" a module, you can run `go get` for that module path and it will be stored in Athens storage forever. After https://github.com/gomods/athens/issues/1068, you would not have to run `go get` (but still could if you wanted to) in order to notify Athens to immediately go download the code.
