### ISSUE TITLE
Background synchronization job for Olympus

### ISSUE THREAD

**Issue by michalpristas** [gomods/athens#107]
To achieve consistency between different Olympus cloud deployments, each of the deployment provides a background job to keep up to speed with its peers.

The first and fundamental background job is meant for pull synchronization. 

Once in every synchronization period background job will start pulling process to learn about the state of other deployments. 
First time it runs it asks for whole history (whole event log). 
On each pull, Olympus remembers exact pointer (last_replicated) to last known event log location of all other deployments and within next pull request provides this information and receives only changes since this point.
This way we can achieve frequent request with a small payload.

After Olympus is aware of event log changes retrieved from other deployments, it then merges those logs into one working log.

This working log is appended with items store in working queue up to the point when current synchronization run started.

At this point working log might contain duplicates which need to be removed by running some deduplication process. 

Once working log is merged and cleaned of duplicates it can be processed which means:
- download module source,
- store in the backing store,
- preparing CDN links,
- appending entries to the main event log.

Prereq: #102

**Comment by arschles** [comment]
I have some ideas on this - design doc incoming as soon as I can. Thanks for pinging me about this @michalpristas !

**Comment by arschles** [comment]
The design document for the gossip protocol is [here](https://docs.google.com/document/d/1R1iCuDUF8FPZpJalewVZMjSaqWOZn37MHjssayQRQs4/edit#)

Note that this document links to [this document](https://docs.google.com/document/d/16oeQp620bn4BrhaV-DvGjoJpVHQkF3bOGEbspCW11t0/edit#), which specifically details metadata exchange

**Comment by michalpristas** [comment]
updated description, based on latest discussions

**Comment by arschles** [comment]
I don't think we should do constant background synchronization, because that requires complex event log logic - like orchestrating log appends with storage updates & log compaction - and I don't anticipate that we'll gain much from the effort.

To recap, we planned to do background sync to increase the probability that at any given time, a given Olympus OM will have package MxV1 if another Olympus OA has it. We have two other mechanisms that I believe give us the same or better up-to-date features, with simpler implementations:

- [push synchronization](https://github.com/gomods/athens/wiki/The-Central-Package-Registry-(Olympus)#push-synchronization). This is essentially OA pushing to OM, OG, and others when it downloads a new MxV2. If it fails to push to a deployment after some retries, it gives up
- [pull synchronization on cache miss](https://github.com/gomods/athens/wiki/The-Central-Package-Registry-(Olympus)#pull-syncronization) this is simply OM getting a cache miss and then asking OA and OG if they have the new MxV2 (before going out to the VCS). Again, no need for an event log here because OM can just say "hey, do you have MxV2?" to OG/OA/...
- [Athens Proxies](https://github.com/gomods/athens/wiki/Proxies-(Athens)). These _do_ use an event log, but the logic is simpler because it doesn't have to be replicated across Olympus deployments (an Athens pins to a specific Olympus on the first request. See [here](https://github.com/gomods/athens/wiki/Proxies-(Athens)#background-jobs) for more info)

**Comment by michalpristas** [comment]
just to point out what we discussed offline: 
Athens proxies will not use event log. they will just check periodically with olympus what happened since last check and deduplicate entries based on Exists check implemented in each storage.

**Comment by arschles** [comment]
As of #772, we're not going to try and build a registry for the time being. Closing
