### ISSUE TITLE
Replace Travis CI

### ISSUE THREAD

**Issue by arschles** [gomods/athens#1077]
**Is your feature request related to a problem? Please describe.**

Recently, Travis CI was acquired and then has laid off some of its employees. Sources:

- https://techcrunch.com/2019/01/23/idera-acquires-travis-ci/
- https://twitter.com/EricaJoy/status/1098595526742814722

This might mean that we won't be able to use Travis anymore for our CI/CD system

**Describe the solution you'd like**

We should think about switching. The first order of business is to see what alternatives suit our needs:

- CircleCI?
    - Check out https://github.com/gomods/athens/pull/1084 for an example
- DroneCI?
- Github Actions?
    - Aaron to find out of GH Actions can spin up background containers so we can do e2e tests etc…
- Google Cloud Build (https://cloud.google.com/cloud-build/)
- Azure pipelines

**Describe alternatives you've considered**

We could stay on Travis and take our chances

**Additional context**

We talked about this in our Feb 21 developer meeting

**Comment by marwan-at-work** [comment]
One question that @fsouza brought up with me: is our Azure pipelines windows only? Because if we already have Azure pipelines set up, then maybe we can just cancel Travis and everything is cool? 

One thing I noticed in our CI/CD pipeline, is that the Azure Pipelines are pretty slow compared to travis 11 minutes vs ~3 minutes, so maybe it'd be a good opportunity to try out different set ups on our own forks and report back with the following 3 comparisons; 

1. How long does the build take? 
2. Can we run background containers? So that we can test storage backend implementations. 
3. How maintainable is the pipeline? Ease of use etc. 

I'd be happy to try DroneCI as I'm familiar with them from my work.

**Comment by arschles** [comment]
@marwan-at-work our Azure pipelines is windows only right now. I'm working on speeding that piece up in #1066. Adding build steps to also do linux builds is separate (and simpler) work, though. It's essentially using our docker-compose file in that case, which would greatly speed up setup times for mongo/minio/etc... I can also get help with pipelines if we need it. I'll submit a PR for adding linux to azure pipelines

**Comment by arschles** [comment]
Regarding Github actions, I've asked internally about whether it can run containers in the background while our tests run. Waiting to hear back at the moment

**Comment by chriscoffee** [comment]
> Regarding Github actions, I've asked internally about whether it can run containers in the background while our tests run. Waiting to hear back at the moment

It supports concurrent workflows, so I wonder if you could possibly have the dependencies (mongo etc) in one workflow and athens in another with `needs` requiring the other action. There'd probably some networking problems here though and don't know if you can need actions across workflows but it'd be cool to test.
