### ISSUE TITLE
@list missing some versions

### ISSUE THREAD

**Issue by xytan0056** [gomods/athens#1305]
**Describe the bug**
google proxy : 
https://proxy.golang.org/github.com/shirou/gopsutil/@v/list
returns
```
v2.0.0+incompatible
v2.16.10+incompatible
v2.16.11+incompatible
v2.16.12+incompatible
v2.17.10+incompatible
v2.17.11+incompatible
v2.17.12+incompatible
v2.18.10+incompatible
v2.18.11+incompatible
v2.18.12+incompatible
v2.19.6+incompatible
```
however, 
https://proxy.golang.org/github.com/shirou/gopsutil/@latest  -> `v2.18.12+incompatible`

as of when the issue if filed, master athens returns
```
$ curl http://localhost:3000/github.com/shirou/gopsutil/@v/list
v2.0.0+incompatible
v2.16.10+incompatible
v2.16.11+incompatible
v2.16.12+incompatible
v2.17.10+incompatible
v2.17.11+incompatible
v2.17.12+incompatible
v2.18.10+incompatible
v2.18.11+incompatible
v2.18.12+incompatible
<-- missing v2.19.6+incompatible
```

`go list` also misses a version. I wonder how google's proxy does it
```
$ GO111MODULE=on go list -m -versions -json github.com/shirou/gopsutil
go: finding github.com/shirou/gopsutil v2.18.12+incompatible
{
	"Path": "github.com/shirou/gopsutil",
	"Version": "v2.18.12+incompatible",
	"Versions": [
		"v2.0.0+incompatible",
		"v2.16.10+incompatible",
		"v2.16.11+incompatible",
		"v2.16.12+incompatible",
		"v2.17.10+incompatible",
		"v2.17.11+incompatible",
		"v2.17.12+incompatible",
		"v2.18.10+incompatible",
		"v2.18.11+incompatible",
		"v2.18.12+incompatible"
	],
	"Time": "2018-12-25T20:55:58Z"
}
```

**Error Message**
none

**To Reproduce**
build from source as instructed and query `github.com/shirou/gopsutil/@v/list`

**Expected behavior**
return the same results as proxy.golang.org

**Environment (please complete the following information):**
 - OS: macos
 - Go version : go1.12.6 darwin/amd64
 - Proxy version : master
 - Storage (fs/mongodb/s3 etc.) : disk

**Additional context**

**Comment by yittg** [comment]
@xytan0056 It's clear, it is about go module semantic versioning.
for all v2+ version, if it is not adopted go module(checking go.mod), it will be marked as incompatible and will be respond for fetch without explicit version(like v2,v3...), 
otherwise for those adopted go module(v2.19.6 you mentioned), it is only in it's major version list(v2)
so for design, `curl http://localhost:3000/github.com/shirou/gopsutil/@v/list` will not contain v2.19.6, for more detail, please reference [Semantic Import Versioning of Go Module](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher).

As for why proxy.golang.org list contains v2.19.6 marked as incompatible, i guess that v2.19.6 was changed before or something else, not quit sure. you could check that v2.19.6 can not be downloaded from proxy.golang.org correctly.

And if you really want same result with proxy.golang.org, you can configure it as GoProxy of athens.

**Comment by marwan-at-work** [comment]
v2.19.6 has a `go.mod` file, yet it doesn't have a `/v2` suffix in its import path. This is a mistake on the `gopsutil` side and they should probably fix it. I'll open an issue there. Thanks
