### ISSUE TITLE
Why athens doesn't cache packages when using GlobalEndpoint and FilterFile?

### ISSUE THREAD

**Issue by Haiyung** [gomods/athens#1418]
Hi,

I am trying to use athens to cache public packages in my local server.

Now, I set GlobalEndpoint,FilterFile and Storage.Disk in athens.toml and then execute go mod tidy. Those packages were downloaded, but not stored in RootPath which I set.

I have to download again and again. In other words, athens' cache does not work.

How should I do?

Thanks.

**Comment by MkAnHui** [comment]
+1

**Comment by arschles** [comment]
Hey @Haiyung and @MkAnHui - we don't have functionality in Athens yet to fill up Athens storage from upstream sources besides version control systems, because there hasn't been a use case for it.

Right now, if you set `GlobalEndpoint`, Athens will return a redirect and tell the Go tool to go and fetch code from the proxy. Do either of you have a use case for making it store the code?

**Comment by marwan-at-work** [comment]
The GlobalEndpoint (bad name for legacy reasons) and the FilterFile are top level that are explicitly for not reaching our storage in any way. 

If you'd like to point Athens to another Public Proxy while still caching the modules, use the DownloadFile documented here: https://docs.gomods.io/configuration/download/

Please feel free to re-open this issue if I misunderstood :)
