### ISSUE TITLE
Push source code into version controll system

### ISSUE THREAD

**Issue by volker-raschek** [gomods/athens#1424]
Hello, I am instructed to keep all libraries that are imported into every golang project of my company in order to be able to create definitively reproducible software. Otherwise there is a danger that libraries on the internet will be deleted or moved and older versions can no longer be built. 

Athens cached the libraries, but it would be nicer if Athens uploaded the libraries to a version control system - be it Bitbucket or Gitlab. This is a feature that my company urgently needs.

Volker

**Comment by arschles** [comment]
Hi @volker-raschek - the major purpose of Athens is to download module code _from_ version control systems and cache them in its own storage, so I have a few questions that maybe you can answer to help me understand your use case:

- Are you looking to have these dependencies in your own version control system so that you can maintain them yourself?
- Would manually forking these dependencies be acceptable for you?

**Comment by volker-raschek** [comment]
> Are you looking to have these dependencies in your own version control system so that you can maintain them yourself?

Yes, but without maintaining. I must only provide third party libraries in our own version control system, because if the library is deleted, developers can't look into the source code they once used for problems.

The following example should explain the workflow for the ssh package, if it's needed as third party lib for a golang project.

![Diagramm1](https://user-images.githubusercontent.com/18311012/67402246-9ab34580-f5b0-11e9-94c0-f0d3ca247649.png)

**Comment by arschles** [comment]
@volker-raschek thanks for the added details. Athens isn't designed to fork code from one repository to another, unfortunately. Instead, it's designed to store code as a downloadable asset, stored in a database, and serve it to the Go CLI tool.

There's no great solution in Athens for what you want to do, but you can get something working by manually downloading all of the module zip files that Athens has stored, unzip each file, and then push them all up to a repository of your choosing.

If you're interested in doing that, let me know and we can talk more about it 😄

**Comment by arschles** [comment]
@volker-raschek I thought of another option that you might be able to take advantage of without modifying Athens. We have a [webhook](https://github.com/gomods/athens/blob/5870aeee8de4cc9922c9592db3934846c91be369/pkg/middleware/validation.go#L16) (which is poorly documented at the moment, that's a work in progress 😄) that we initially called a "validation webhook".

The use case we originally intended it for was to reach out to any HTTP server to determine if it's ok for Athens to download and store a module. Since Athens is sending an HTTP request every time it is ready to download a new module, you could have an HTTP server that responds to those webhooks and does the forking logic that you need.

If you do decide to go with that approach, I can document it much better on our docs.gomods.io site.

Can you let me know what you think about that?

**Comment by arschles** [comment]
@volker-raschek I am going to close this issue, but we're happy to continue the conversation. If you'd like to do so, can you comment here or open a new issue? Thanks!
