### ISSUE TITLE
Fix build flakes

### ISSUE THREAD

**Issue by arschles** [gomods/athens#1478]
**Describe the bug**

We have had consistent build flakes in drone.io such as https://cloud.drone.io/gomods/athens/1283/1/5. Errors manifest themselves like this:

- [build step 5](https://cloud.drone.io/gomods/athens/1281/1/5) succeeds, but Athens can't connect to the Google Cloud Storage bucket because it doesn't have the proper credentials (I think, based on the error message). This step should fail
- [build step 6](https://cloud.drone.io/gomods/athens/1281/1/6) fails because the Athens server isn't actually running 😦 

**Error Message**

```
error getting storage configuration (could not create new storage client: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.)
```

**To Reproduce**

This is a flake, so not consistently reproducible, but https://cloud.drone.io/gomods/athens/1281/1/5 is a great example.

**Expected behavior**

Builds that should fail always fail, and builds that should pass always pass.

**Environment (please complete the following information):**

N/A - this is for CI/CD builds

**Additional context**
None

**Comment by marwan-at-work** [comment]
@arschles 

The error you see in the logs I believe are coming from this line: https://github.com/golang/oauth2/blob/master/google/default.go#L117

But this line is only executed if there were no credentials provided. And when no credentials are provided, we attempt to go for the default ones. 

The athens image we're running takes these params: 

```
    ATHENS_STORAGE_GCP_JSON_KEY:
      from_secret: GCS_SERVICE_ACCOUNT
```

So it's one of the following possibilities: 

1. The secret got updated to an empty string in our ci settings 
2. Drone has a bug where it's not passing this correctly 
3. Athens has a bug where it's not picking up the environment variable correctly 


I almost thought 3 was not correct, but I think it is. I had an old version of the `canary` image, and it worked as expected, but when I updated canary, it broke. See here: 

```
MacBook-Pro:gcp marwansulaiman$ docker run --rm -e 'ATHENS_GOGET_WORKERS=5' -e 'ATHENS_PROTOCOL_WORKERS=10' -e 'ATHENS_STORAGE_TYPE=gcp' -e 'ATHENS_STORAGE_GCP_BUCKET=athens_ci_build' -e 'ATHENS_STORAGE_GCP_JSON_KEY=asdfasdf' gomods/athens:canary
2019-12-04 03:24:01.954224 I | error getting storage configuration (could not get GCS credentials: invalid character 'j' looking for beginning of value)
MacBook-Pro:gcp marwansulaiman$ docker pull gomods/canary:latest
Error response from daemon: manifest for gomods/canary:latest not found: manifest unknown: manifest unknown
MacBook-Pro:gcp marwansulaiman$ docker pull gomods/athens:canary
canary: Pulling from gomods/athens
89d9c30c1d48: Already exists
c34dcbc70547: Pull complete
7c4b5d273be6: Pull complete
5460a1e9b2cc: Pull complete
fc7b6ecb96c4: Pull complete
Digest: sha256:d258861fcea9a9f0aef18753166dfebef441deb6a879b27f0fc8a828c5faa248
Status: Downloaded newer image for gomods/athens:canary
docker.io/gomods/athens:canary
MacBook-Pro:gcp marwansulaiman$ docker run --rm -e 'ATHENS_GOGET_WORKERS=5' -e 'ATHENS_PROTOCOL_WORKERS=10' -e 'ATHENS_STORAGE_TYPE=gcp' -e 'ATHENS_STORAGE_GCP_BUCKET=athens_ci_build' -e 'ATHENS_STORAGE_GCP_JSON_KEY=asdfasdf' gomods/athens:canary
2019-12-04 03:24:34.130490 I | error getting storage configuration (could not create new storage client: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.)
````

So one of  the recent commits broke us 😄 

It seems like it's this last commit:

### Breaking Change: https://github.com/gomods/athens/commit/e0ec46b2213b3b715bf27a9a401b9f4300ec9d75

This is a breaking change that we should revert before doing any release

This was renamed here so any new release will break all existing Athens users: https://github.com/gomods/athens/commit/e0ec46b2213b3b715bf27a9a401b9f4300ec9d75#diff-422a9f62303968af1694a4097c7fb5b2R311

This was also renamed so any existing Athens users will be just as confused as I just was because I wasn't sure why the credentials weren't being picked up: https://github.com/gomods/athens/commit/e0ec46b2213b3b715bf27a9a401b9f4300ec9d75#diff-c082128b4f0b4bbd252579501ecce827R7

Is there a strong case for changing these names? Does it clash with anything else?

**Comment by marwan-at-work** [comment]
CC: @epk
