### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by DylanMeeus** [gomods/athens#1571]
Recently I deployed an instance of athens to Google Cloud, and I believe the docs could be updated a bit. 

1) Versioning is out-of-date, blindly following the docs at first I ended up with `v0.6.0` rather than `v0.7.2`

2) A `Dockerfile` is needed when you use `gcloud submit`, but this step wasn't found in the docs for `Google Cloud Run`, which I eventually did see in the `Google  App Engine` docs.

3) A minor one, and this is perhaps more my mistake than the docs, but copy-pasting the command:
```$ gcloud beta run deploy \
    --image gcr.io/$GOOGLE_CLOUD_PROJECT/athens:v0.6.0 \
    --platform managed \
    --region $ATHENS_REGION \
    --allow-unauthenticated \
    --set-env-vars=ATHENS_STORAGE_TYPE=gcp \
    --set-env-vars=GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT \
    --set-env-vars=ATHENS_STORAGE_GCP_BUCKET=$GCS_BUCKET \
    athens
```

does not work, as the region specifier of GCP is missing. (`gcr.io` -> `[region].gcr.io`). Someone with more experience using GCP would probably have seen this faster, but perhaps the docs should mention it?

There's also some typos on those pages. :sweat_smile:

(If these changes are OK, I can update the Hugo markdown files. I suppose that's all that needs to happen?)

**Comment by marwan-at-work** [comment]
@DylanMeeus thank you for reporting this issue. A PR would be great! 

Though I've run Athens on cloud run a number of times, I didn't know we had docs on it 😄 

> Versioning is out-of-date

I think we should put `x` instead of the version number, otherwise we'd always have to update this document. We can also say `check the latest upgrade, below is just an example`

> A Dockerfile is needed 

I'm not sure what you mean, the docs mention that you can just pull the gomods/athens image from Docker Hub, and re-tag it with `gcr.io` and push it back...in that case, there's no need for a Dockerfile at all no? 

> gcr.io -> [region].gcr.io

You should be able to just use `gcr.io`, I believe it's the global one. But let me know why that fails

**Comment by DylanMeeus** [comment]
@marwan-at-work 

If you submit to GCR with this command:
```
$ gcloud builds submit --tag gcr.io/$GOOGLE_CLOUD_PROJECT/athens:vx.y.z
```

The exact error is: 
```
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /workspace/Dockerfile: no such file or directory
```

So I assume the docker file would still be needed, somehow. The error was also resolved by simply using a Dockerfile. 

`grc.io` didn't work for me either (image not found in cloud regsitry) but `eu.grc.io` did. I'm not ruling out that this is because of the gcloud version I have installed, it's not an athens problem at all of course. :)

**Comment by marwan-at-work** [comment]
@DylanMeeus I think `gclouds builds submit` are specifically for building an image from scratch and pushing it (as opposed to pushing an already built image)

The docs for pushing/pulling images mention that you just need to use `docker push` https://cloud.google.com/container-registry/docs/pushing-and-pulling

**Comment by marwan-at-work** [comment]
cc: @schafer14 as I'm not sure if `gclouds builds submit` can be used to push an already built image

**Comment by DylanMeeus** [comment]
Aha I see. (the same docs you linked also talk about the region specifier as separating storage buckets by the way). I thought it worked when I did the `gcloud build submit`, or at least, it did not error out. 

I did have some trouble with the next step (`gcloud beta run deploy`) and fiddled around with more stuff at that point.

**Comment by schafer14** [comment]
Hey, sorry for the late response. Thanks for the feedback and PR! 

Just to add my two cents about the `gcloud build subit` issue. The goal of this step is to get an Athens container into GCR (google container registry) so it can be accessed by Cloud Run. You could use the Athens Dockerfile to build the container and then push it to GCR and that would accomplish the same outcome. There is already an Athens container on DockerHub so pulling that down and pushing it back up to GCR seems easier.

It sounds like you resolved your problem? What I suspect was the problem was a mismatch in the tags used once they were updated to the new version.

@DylanMeeus does this help clear things up? 

@marwan-at-work is this consistent with your understanding?

**Comment by marwan-at-work** [comment]
@schafer14 

> There is already an Athens container on DockerHub so pulling that down and pushing it back up to GCR seems easier

I agree, but I don't think `gcloud builds submit` works in this case right? I think `gclouds builds submit` is explicitly for building an image from a Dockerfile, and not pushing an already built image?

**Comment by schafer14** [comment]
@marwan-at-work I think you're correct... I have no clue what I was thinking. 

I think this is what we are looking for?

```
gcloud docker -- push gomods/athens:v0.6.0 gcr.io/$GOOGLE_CLOUD_PROJECT/athens:v0.6.0
```

**Comment by DylanMeeus** [comment]
@schafer14 that command will not be supported for more recent docker versions it seems.
```
(WARNING: `gcloud docker` will not be supported for Docker client versions above 18.03.)
```

and is seemingly replaced by just using `docker push` (`docker push gcr.io/example-org/example-image:latest`)

See the bottom of this page: https://cloud.google.com/sdk/gcloud/reference/docker

**Comment by StevenACoffman** [comment]
This... didn't exactly happen in the PR. Corrected instructions should be:

```
$ docker pull gomods/athens:v0.7.2
$ docker tag gomods/athens:v0.7.2 gcr.io/$GOOGLE_CLOUD_PROJECT/athens:v0.7.2
$ docker push gcr.io/$GOOGLE_CLOUD_PROJECT/athens:v0.7.2
```
