### ISSUE TITLE
[Proposal] Remove storage.Checker from storage.Backend

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#1578]
The storage.Backend interface has an `Exists` method which is part of the storage.Checker interface. 

This is used to check if a module exists. However, the Go command itself uses the `Info` endpoint to check if a module exists, it even calls it [Stat](https://github.com/golang/go/blob/971f8a2f9a5beb0473f82d7299613c86d2b4a5b9/src/cmd/go/internal/modfetch/proxy.go#L354)

There are a couple of good reasons to remove `Exists` from our storage API: 

1. Keeping the interface smaller makes implementing new storages easier. 
2. With the external storage that will land soon, we should make it as easy as possible for people to integrate their own storage solutions. 
3. The Info endpoint will always be a small json blob that should not be much of an overhead to use instead of the Exists call. 

Storage implementations right now can still use Exists to validate for whatever logic they need, but they certainly can be optimized to just return KindNotFound instead of making extra calls.

**Comment by arschles** [comment]
@marwan-at-work sounds fine to me

I definitely like #1580 better than #1579 (looks like that is the alternative) because external storages can opt into using `Exists` if that that's more efficient for them. I wrote a few more details about that in https://github.com/gomods/athens/pull/1579#pullrequestreview-377128503
