### ISSUE TITLE
Minimum S3 permissions 

### ISSUE THREAD

**Issue by thomasrutkowski** [gomods/athens#1694]
**Is your feature request related to a problem? Please describe.**
When setting up Athens with AWS S3 storage backend, the documentation fails to specify necessary permissions for the bucket. Best practice is to only allow the minimum permissions needed. 

**Describe the solution you'd like**
A list of permissions or optimally a policy snippet included in the documentation.

**Describe alternatives you've considered**
The easy way out is to add all permissions to a policy.
The hard way is to try and figure out which permissions are needed by reading the source and/or by trial and error.

**Comment by arschles** [comment]
@thomasrutkowski from memory, you'll need just read and write on a bucket. I want to confirm - is that what you're seeing? If so, I can update the docs

**Comment by thomasrutkowski** [comment]
Hi, 
I'm currently testing and setting the environment up, I can set up a PR with examples and instructions towards the documentation unless you would prefer a snippet here?

**Comment by thomasrutkowski** [comment]
Tested and verified working IAM-policy:

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::BUCKETNAME"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::BUCKETNAME/*"
        }
    ]
}`

**Comment by thomasrutkowski** [comment]
Hi @teochenglim, 

We are using an instance profile with the above policy attached. If your Bucket is encrypted you would also need to add kms-keys for decrypt. 

I set AWS_USE_DEFAULT_CONFIGURATION=true for athens to work with the instance profile and consequently do not set AWS_ACCESS_KEY_ID or AWS_SECRET_ACCESS_KEY at all. 

I would recommend that you join the #athens channel on the gophers slack.

**Comment by teochenglim** [comment]
Guys.. it still doesn't work on EKS because it is not using sts assume role, but it used sts web assume identify.

**Comment by marwan-at-work** [comment]
I'm happy to re-open this issue as well. But I'm not too familiar with AWS and its permission model.

@thomasrutkowski can you please confirm @teochenglim 's concern given your docs PR that closed this issue? 

Thanks! 🙏🏼

**Comment by teochenglim** [comment]
@marwan-at-work allow me to explain in long details.

Thomas is using ec2 instance (VM) and it works on ECS (docker container managed service) works for him. It is a good documentation for the user to have.

I am using EKS (Kubernetes manage service) and it doesn't work for me.

In AWS you can use API_KEY and API_SECRET to authenticate the AWS "session" https://github.com/gomods/athens/blob/main/pkg/storage/s3/s3.go#L68 and https://github.com/gomods/athens/blob/main/pkg/storage/s3/s3.go#L50-L51. 

You can also use AWS instance profile if you are using VM/ECS that doesn't required API_KEY and API_SECRET. The EC2 (VM) will trigger something like "sudo" called sts.assumeidentify using the given profile.

On EKS side, because it is a pod need the permission and not the host, we use openid connect, sts.webassumeidentify way to bind the AWS role to a pod. Same thing, no API_KEY and API_SECRET is given and the pod can assume the permission , details here
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html

in most of the cases for EKS to work, it is just like setting the aws region and then connect shall just work
setup region: https://github.com/gomods/athens/blob/main/pkg/storage/s3/s3.go#L39
new session https://github.com/gomods/athens/blob/main/pkg/storage/s3/s3.go#L68

But I look at the source code I really doesn't know what's wrong and why it didn't connect. And no error is generated so no where to debug also.

Meanwhile I am using Key and Secret as a work around.

**Comment by teochenglim** [comment]
@marwan-at-work 

working code for EKS

```go
//NewSession ...
func NewSession(cfg *Config) (*session.Session, error) {
	if cfg.Region == nil {
		cfg.Region = aws.String("us-west-1")
	}
	return session.NewSession((*aws.Config)(cfg))
}

//S3 is a wrapper of s3.S3
type S3 struct {
	*s3.S3
	uploader   *s3manager.Uploader
}

//NewS3 return a new S3 instance
func NewS3(sess *session.Session, cfg *Config) *S3 {
	svc := s3.New(sess, (*aws.Config)(cfg))

	uploader := s3manager.NewUploader(sess)

	return &S3{
		S3:         svc,
		uploader:   uploader,
	}
}


```
