### ISSUE TITLE
opentracing: fix operation name in olympus

### ISSUE THREAD

**Issue by bketelsen** [gomods/athens#172]
by setting operation name explicitly in handlers

**Comment by robjloranger** [comment]
Also maybe the service name should be changed from `athens` to `olympus`.
ref: https://github.com/gomods/athens/blob/ab9a4c0f4197d7e721a757250e506eae611d08c3/cmd/olympus/actions/tracing.go#L31

**Comment by manugupt1** [comment]
this is similar to the tracing stuff I am working on. I can take this as well! Most of commits now have an operation name. If it is similar to the following commit,
https://github.com/gomods/athens/blob/master/pkg/storage/s3/storage.go#L80

I can make the changes and push it.

cc @bketelsen @robjloranger

**Comment by robjloranger** [comment]
Abosultely @manugupt1, if your interested please open a PR.

It's a bit different, it's not starting the span but setting the operation name because the handlers won't automatically have that set. see #338 for examples setting operation names. All handlers in both the registry and proxy should have the operation name set explicitly.

also for reference discussion where I was confused: #339

**Comment by manugupt1** [comment]
Check this out @robjloranger  Every handler has an opName attached 
https://github.com/bketelsen/buffet/blob/master/opentracing.go#L22

The issue in my code is that
It is not really a child span of the context 
https://github.com/gomods/athens/blob/master/pkg/storage/s3/storage.go#L80

This can be fixed when we start using buffet in these functions that have a context that start a childspan of the context that is passed down below the handler
https://github.com/bketelsen/buffet/blob/master/opentracing.go#L109-L117

So, really the changes that I am thinking is

The initialize function should take the app name as a parameter 
https://github.com/gomods/athens/blob/master/cmd/proxy/actions/app.go#L100
and set it here
https://github.com/gomods/athens/blob/e76125d3f1d42081cbaacb5606223907795cd478/actions/tracing.go#L31

The next step would be to start using every function that has a context use buffet
https://github.com/bketelsen/buffet/blob/master/opentracing.go#L109-L117 with an opname

the final step would be commonizing that entire thing
https://github.com/gomods/athens/issues/348


Does that sound like a good plan of action?

**Comment by robjloranger** [comment]
I think this issue should stay on topic, keep it small.

I know that buffet sets an operation name for handlers automatically, however, because of the way we create our handlers buffet treats them more like regular functions and does not set an operation name.

As for the the initialize function it can just be hard coded in `tracing.go` as each app has it's own tracing initializing function.

**Comment by manugupt1** [comment]
Perfect, I did not realize that `initializetracing` is within the context of every app! I can put in a PR in a while at least for that.

**Comment by manugupt1** [comment]
Ref: https://github.com/gomods/athens/issues/392

**Comment by manugupt1** [comment]
This should fix it @arschles 
https://github.com/gomods/athens/commit/7aafc2692e449c13ce16605e696fbb75a099a2d5

**Comment by robjloranger** [comment]
correct, closed by #384
