### ISSUE TITLE
switch to envconfig for configuration 

### ISSUE THREAD

**Issue by arschles** [gomods/athens#284]
the `./pkg/config/env` package has lots and lots of `envy.Get` (and friends) calls, with defaults, type conversions, etc...

let's remove all that duplicated code and use [envconfig](https://github.com/kelseyhightower/envconfig)

**Comment by marwan-at-work** [comment]
@arschles Should we have a config struct with all of our expected environment variables?

**Comment by robjloranger** [comment]
I think so @marwan-at-work. What do you think about using an init to first load the config, then the subsequent calls can return needed variables?

**Comment by michalpristas** [comment]
👍 for a configuration file. keep dev defaults there. we can inject/replace the file with test/prod env easily on deploy

**Comment by marwan-at-work** [comment]
What about having a json or toml representation of that config struct and so instead of populating env variables and keeping track of them, we just have one file where all this stuff lives. 
Something like this 

```golang
type Config struct {
  GoBinPath string
  OlympusGlobalURL string
  DebugLevel string
  ...
}
```

And then we can have several json representations for different environments: 

config.local.json
```json
{
  "GoBinPath": "go",
  "OlympusGlobalURL: "http://localhost:3001",
  "DebugLevel": "debug"
}
```

and then config.prod.json

```json
{
  "GoBinPath": "go",
  "OlympusGlobalURL": "https://www.olympus.com",
  "DebugLevel": "warning"
}
```

This way we don't need envconfig, or we can use it for overrides in the config if we really want to. Which is cool w/ me.

**Comment by rchakra3** [comment]
I'll work on this!
