### ISSUE TITLE
proposal: rename pkg/cdn

### ISSUE THREAD

**Issue by robjloranger** [gomods/athens#325]
`pkg/cdn` is really just metadata drivers, so I propose that we rename this package. Similar to `pkg/storage`.

The contents of `pkg/cdn/metadata` would be moved to into `pkg/cdn`, the now empty `pkg/cdn/metadata` would be deleted and then the package directory `pkg/cdn` would be renamed to `pkg/metadata`.

Then all references would need to be updated to reflect the new package path.

**Comment by arschles** [comment]
Agree - after we rename or merge somehow with `./pkg/storage/cdn` or something else (#299) we should document how we use CDNs because it's confusing. here are the ways:

- we use the CDN as a web server that we redirect vgo to. the web server implements the download protocol
- we use the CDN as a database that we use to store zip, info and mod files in

sidenote: I wonder if there's a way to combine these two concepts? like, for example can we somehow wrangle the second one into the first one?

**Comment by arschles** [comment]
This seems like it’ll make things a little more understandable in our
codebase so +1 from me

**Comment by marpio** [comment]
@arschles so if the proxy doesn't have the module in cache, it asks Olympus for it and gets a URL to which vgo can be redirected. Is that what you mean? 
If that is the case, what happens if Olympus doesn't have it - does proxy wait until

**Comment by michalpristas** [comment]
closing: package removed
