### ISSUE TITLE
introduce logging middleware

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#328]
now that we have our own logger, we should introduce a Buffalo middleware for our logger that injects sane default into a log `Entry`. This is so that whenever there's a SystemErr not only do you see the information about the error (module, operation etc), you see the request details that caused this error: http-path, http-method, request-id etc. 

The question now is that should we pass the logger through the context (requires no update to function signatures, but is kind of magical and *not* type safe)

Or should we update the function signatures of our buffalo handlers to take a log Entry?

**Comment by robjloranger** [comment]
I'm thinking update the handlers, I'm not a fan of magic 😬

**Comment by arschles** [comment]
+1 to @robjloranger - I definitely think we should pass loggers into the handlers by updating them, rather than in the context. I think it's a little more work to write but later on, easier to read. All that is subjective of course :)

Regarding the middleware, I like this idea but there's also a buffalo logger built in ([here](https://github.com/gomods/athens/blob/27bbc3f42f683da78d766361656caaf270b6748a/cmd/proxy/actions/app.go#L97)) - would it make sense to implement our own?

**Comment by marwan-at-work** [comment]
@arschles we already implement our own, which is what `log.Buffalo()` returns. This is only for dev purposes as we should not log anything from buffalo in production.

**Comment by marwan-at-work** [comment]
@arschles @robjloranger to be clear, this logging middleware should not *log* anything to Stdout. It should only populate the logger with sane Entry Fields :)
