### ISSUE TITLE
proxy: support authenticated proxies

### ISSUE THREAD

**Issue by ajstarks** [gomods/athens#587]
Note that this issue is probably related to #310, some environments have all outside Internet access mediated by an NTLM authenticated proxy.  Athens should support this use-case

**Comment by timraymond** [comment]
I did a little research here since I had never heard of NTLM before :) The exchange that needs to happen between `go`, the proxy, and the outside world needs to look like this in an NTLM-authenticated world:

![ic871898](https://user-images.githubusercontent.com/288061/45527739-39188900-b7ab-11e8-8633-010e5830fc67.png)

I pulled the above from [MSDN](https://msdn.microsoft.com/en-us/library/dd925287(v=office.12).aspx), and there's quite a bit of detail there.

One challenge here will be setting up a minimum-viable NTLM proxy + Active Directory-equivalent to develop against. I found [this project](http://cntlm.sourceforge.net/) which may be able to help with the proxy part. @ajstarks are you aware of any other alternatives which might help with developing this?

The other challenge is going to be getting `go` to do this exchange. One possible idea would be to shim `go`'s upstream connection with a local http proxy (via the `http_proxy` ENV?) that performs this exchange with the bastion proxy.

**Comment by ajstarks** [comment]
Yes, I know about cntlm but I have never used it. By the way, curl lets you do this:

```
curl --proxy [host:port] --proxy-ntlm -U[user:password]
```

The ideal case is for Athena to support this internally without other tools, of course

**Comment by arschles** [comment]
@ajstarks did you figure out a way around this?

**Comment by ajstarks** [comment]
Sorry, no.

**Comment by arschles** [comment]
Just dropping a quick note in here - we haven't forgotten about this issue, but not planning to implement it at the moment. @ajstarks or anyone else interested - can you please 👍 this comment, or add your own comment if you need this functionality for your production Athens deployments?

**Comment by ajstarks** [comment]
I currently don't need this now, so I'm ok with lowering the priority.

**Comment by arschles** [comment]
@ajstarks I am going to close this, since you don't need it now. If it comes back up, comment here and I'll get the notification and come open the issue back up.

**Comment by arschles** [comment]
just going to throw this in here: https://github.com/genotrance/px

This could potentially be a good way for Athens to download from VCS's via HTTP, and from upstream proxyes (which already use HTTP as we know)
