### ISSUE TITLE
Force HTTPS on the gomods site

### ISSUE THREAD

**Issue by arschles** [gomods/athens#597]
Right now, if you go to `http://docs.gomods.io`, it won't force you to HTTPS. See attached screenshot.

<img width="976" alt="screen shot 2018-08-30 at 4 04 36 pm" src="https://user-images.githubusercontent.com/70865/44881904-78ed5580-ac6e-11e8-8799-0dc5e4b55252.png">

**Comment by Sjeanpierre** [comment]
Hi @arschles I submitted a PR for this issue which should correct the behavior described on the production URL using redirects. 

When testing this solution on the staging site, it does not appear to work due to the static url value I have set for the redirect. Would you prefer we do a more global redirect which would solve this issue no matter what URL the docs site is running on?

**Comment by robjloranger** [comment]
closed via #600
