### ISSUE TITLE
vendoring

### ISSUE THREAD

**Issue by bketelsen** [gomods/athens#73]
sort out vendoring
Ideally, a vgo based solution would be best, but how viable is that with buffalo in current configuration?  Research what buffalo dev does and how deep the dep integration is with buffalo.

**Comment by arschles** [comment]
:+1: - afaik buffalo only generates a dep file to manage dependencies for the code it generates, but uses `go get` to build binaries that it needs when running `buffalo dev`

**Comment by arschles** [comment]
Ref https://github.com/gobuffalo/buffalo/issues/981

**Comment by gedw99** [comment]
Vgo is working really well for my projects.
When used with make.go the 2 solve a myriad of issues for ops and CI also.

Mage.go replaces all makfiles with golang equivalents. This makes it very easy to use golang and vgo on Windows and Linux at the same time.
Then for your consideration and ops you need nothing on any machines because mage is you CLI to everything.

**Comment by arschles** [comment]
Check it: https://github.com/gobuffalo/buffalo/pull/1074

**Comment by gedw99** [comment]
I changed to using buffalo grift. Works better than mage.
Buffalo is really quite something

**Comment by arschles** [comment]
@gedw99 would you be interested in trying this out?

**Comment by arschles** [comment]
I'm closing this because #371 and #378 are both going to move us to Go modules after 1.11 stable is out.
