### ISSUE TITLE
Use Azurite to test Azure Storage

### ISSUE THREAD

**Issue by marpio** [gomods/athens#820]
**Is your feature request related to a problem? Please describe.**
At the moment we skip the Azure Storage tests in our travis builds.

**Describe the solution you'd like**
Idea stolen from @chriscoffee 
We could use Azurite https://github.com/Azure/Azurite to test the storage just like we test s3 using minio.

**Describe alternatives you've considered**
Using Azure Blob Storage.

**Comment by chriscoffee** [comment]
I'll take this please

**Comment by t-tomalak** [comment]
I think that with skip azure blob storage tests because it still not implemented `storage.Backend` interface (https://github.com/gomods/athens/issues/703), after that it could use `storage/compliance` tests and use `Azurite`. So this issue should wait or here we could just configure `Azurite` in our docker-compose file. :slightly_smiling_face:

**Comment by michalpristas** [comment]
Yes indeed, the original purpose of the package was a bit different, we need to complete the interface implementation and then enable them in tests (same PR or followup).

**Comment by marpio** [comment]
Waiting for #703

**Comment by chriscoffee** [comment]
I think what I'll do then is task out this into doing the work to add the test and adding the container so I can get the latter half of the task done now.

I'll also check in with #703 and see if they want to pair/help with getting the task completed, we can probably learn something off each other. 

If not I'll just wait.

👍
