### ISSUE TITLE
Feature: Serve as a proxy for the go tool

### ISSUE THREAD

**Issue by bketelsen** [gomods/athens#9]
if a user sets the GOPROXY environment variable to our domain name, they should use our service to download modules, zip files, metadata, etc from our servers where it is cached from the upstream sources.

This reduces load on upstream VCS servers, and allows us to provide a better experience for end-users by using a CDN for content.

**Comment by arschles** [comment]
@bketelsen we said in the [registry section](https://github.com/gomods/athens/blob/master/DETAILS.md#the-registry) that if a user specifies a vanity name, then the VCS name of their module will not be available.

That rule would make the world look like this:

1. I connect my `github.com/my/module` repo to athens (this is always required, whether we're proxying or serving as a registry)
1. Athens by default proxies to `github.com/my/module`
1. I tell athens that I want my GH repo to have a vanity name `rad/module`
1. `go get github.com/my/module` no longer works (because we've said you can either have a vanity name or we'll proxy)

I see two solutions to the problem you posed (reducing load on upstream VCS servers and serving from a CDN):

1. Allowing users to specify a vanity name and keep their VCS-based name
1. Remove proxying altogether and always cache upstream VCS code
    1. We could roughly enable this with the [webhook flow](https://github.com/gomods/athens/blob/master/DETAILS.md#travis-or-other-ci-systems-webhook)
    1. There might be even fancier ways to do this, like automatically pulling tags from GH as they're created

**Comment by robjloranger** [comment]
would this be solved by #238?

**Comment by arschles** [comment]
I think it is? @bketelsen can you close if you agree?

**Comment by michalpristas** [comment]
@bketelsen ping pong

**Comment by arschles** [comment]
This is currently how the proxy works, and when we're running on a public domain name (we are currently doing that with an experimental server, but see #772 for more concrete plans), developers will set GOPROXY to the new DNS entry. Closing
