### ISSUE TITLE
Public proxy response times for Europe

### ISSUE THREAD

**Issue by chriscoffee** [gomods/athens#926]
The current response times for Europe uncached or on the `/list` view which we know has problems are lenghty.

I can't see what the server sees but for various calls it's taking `30+s` against the publically hosted proxy compared to one I'm hosting myself in Europe.

I'd like to have us deploy a public version of the proxy closer to this side of the pond 👍

**Comment by robjloranger** [comment]
What about a geographic load balancing and two deployments to start. North America and Europe.

They would each have their own storage of course which would help us get messaging and replication across deployments working.

**Comment by arschles** [comment]
@robjloranger azure.athensfd.net is now running behind a caching proxy that does geographical load balancing (https://docs.microsoft.com/en-us/azure/frontdoor)

The script to deploy to all the backend regions (as of this writing, I'm doing east US, west europe and southeast asia) is at https://github.com/arschles/athens-azure.

I'm going to close this because the remaining work is caching the mutable endpoints like `/list` and `/latest`, which is #893
